version: '3'
services:
  web:
    container_name: web
    image: letelumiere/squadmania-auth-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: letelumiere/squadmania-auth-nginx
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    container_name: redis
    image: letelumiere/squadmania-auth-redis:v1
    ports:
      - 6379
    depends_on:
      - web

  mysql:
    container_name: mysql
    image: letelumiere/squadmania-auth-mysql:v1
    restart: always
    volumes: 
      - ./data/mysql/:/var/lib/mysql
    environment:
      ## - MYSQL_ROOT_HOST='%' 
      ##- MYSQL_USER=${MYSQL_USER}
      ##- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
      ##- MYSQL_DATABASE='squadmania'
      ## - ports="3306:3306"
    depends_on:
      - web
