services:
  web:
    container_name: web
    image: letelumiere/squadmania-auth-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: letelumiere/squadmania-auth-nginx
    ports:
      - 7000:80
    depends_on:
      - web

  redis:
    container_name: redis
    image: letelumiere/squadmania-auth-redis:v1
    ports:
      - 6379
    depends_on:
      - web

  db:
    image: letelumiere/squadmania-auth-mysql:v1
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    command: --port=${MYSQL_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
