spring:
  output:
    ansi:
      enabled: always
  profiles:
    include: database, oauth2
  #config:
    #import:
    #  - classpath:/application-database.yml
    #  - classpath:/application-oauth2.yml
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


