server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/squadmania?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
        registration:
#          google:
 #           client-id: # 발급 받은 client-id #
 #           client-secret: # 발급 받은 client-secret #
 #           scope: # 필요한 권한 #
          kakao:
            client-name: kakao
            client-id: f66ad78db368781970e4086debb56661
            client-secret: y4Rv3gbKYIJdcyLZbtY6VGVnLdlhnkY7
            client-authentication-method: POST
            redirect-uri: "http://localhost:8080/api/v1/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
