version: '3'
services:
  web:
    container_name: web
    image: letelumiere/squadmania-auth-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: letelumiere/squadmania-auth-nginx
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    container_name: redis
    image: letelumiere/squadmania-auth-redis:v1
    ports:
      - 6379
    depends_on:
      - web

  mysql:
    container_name: mysql
    image: letelumiere/squadmania-auth-mysql:v1
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      HOST : database-1.cel9rnw4ro7a.ap-northeast-2.rds.amazonaws.com
      MYSQL_HOST : ${secret.HOST}
      MYSQL_USER : ${secret.DOCKER_USERNAME}
      MYSQL_ROOT_PASSWORD : ${secret.DOCKER_PASSWORD}
